service: srilanka-staging

servers:
  web:
    hosts:
      - <%= ENV['HETZNER_HOST'] %>

proxy:
  host: staging.srilanka.lv
  ssl:
    certificate_pem: KAMAL_PROXY_TLS_CERT
    private_key_pem: KAMAL_PROXY_TLS_KEY

env:
  clear:
    NEXT_PUBLIC_SELF_URL: https://staging.srilanka.lv
    NEXT_PUBLIC_SANITY_STUDIO_DATASET: production
    SENTRY_ENVIRONMENT: staging
