service: srilanka-development

servers:
  web:
    hosts:
      - <%= ENV['HETZNER_HOST'] %>

proxy:
  host: development.srilanka.lv
  ssl:
    certificate_pem: KAMAL_PROXY_TLS_CERT
    private_key_pem: KAMAL_PROXY_TLS_KEY

env:
  clear:
    NEXT_PUBLIC_SELF_URL: <%= ENV.fetch('NEXT_PUBLIC_SELF_URL') %>
    NEXT_PUBLIC_SANITY_STUDIO_DATASET: <%= ENV.fetch('NEXT_PUBLIC_SANITY_STUDIO_DATASET') %>
    SENTRY_ENVIRONMENT: <%= ENV.fetch('SENTRY_ENVIRONMENT') %>
