import { createThemeContract } from '@vanilla-extract/css';

export const vars = createThemeContract({
  color: {
    background: null,
    foreground: null,
    primary: null,
    primaryForeground: null,
    secondary: null,
    secondaryForeground: null,
    accent: null,
    accentForeground: null,
    error: null,
    errorForeground: null,
  },
  font: {
    family: {
      body: null,
      display: null,
    },
    size: {
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      '2xl': null,
      '3xl': null,
      '4xl': null,
      '5xl': null,
      '6xl': null,
      '7xl': null,
      '8xl': null,
      '9xl': null,
    },
    weight: {
      thin: null,
      extralight: null,
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
    },
    letterSpacing: {
      tighter: null,
      tight: null,
      normal: null,
      wide: null,
      wider: null,
      widest: null,
    },
    lineHeight: {
      none: null,
      tight: null,
      snug: null,
      normal: null,
      relaxed: null,
      loose: null,
    },
  },
  spacing: {
    '0': null,
    '1': null,
    '2': null,
    '3': null,
    '4': null,
    '5': null,
    '6': null,
    '8': null,
    '10': null,
    '12': null,
    '16': null,
    '20': null,
    '24': null,
    '32': null,
    '40': null,
    '48': null,
    '56': null,
    '64': null,
  },
  border: {
    radius: {
      small: null,
      medium: null,
      large: null,
    },
  },
  focus: {
    color: null,
    width: null,
    offset: null,
  },
  shadow: {
    none: null,
    small: null,
    medium: null,
    large: null,
  },
  transition: {
    easing: {
      easeInOut: null,
    },
    duration: {
      slow: null,
      normal: null,
      fast: null,
    },
  },
  zIndex: {
    '0': null,
    '10': null,
    '20': null,
    '30': null,
    '40': null,
    '50': null,
    auto: null,
  },
  breakpoint: {
    xxs: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
  },
});
