/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TagsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tags";
};

export type FaqsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faqs";
};

export type BlogPosts = {
  _id: string;
  _type: "blogPosts";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  excerpt?: string;
  body?: BlockContent;
  tags?: Array<
    {
      _key: string;
    } & TagsReference
  >;
  publishedAt?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqsReference
  >;
  seo?: Seo;
  openGraph?: OpenGraph;
};

export type OpenGraph = {
  _type: "openGraph";
  openGraphTitle?: string;
  openGraphDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageGallery)
  | ({
      _key: string;
    } & StlTableBlock)
  | ({
      _key: string;
    } & YouTube)
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Pages = {
  _id: string;
  _type: "pages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: BlockContent;
  seo?: Seo;
  openGraph?: OpenGraph;
};

export type Faqs = {
  _id: string;
  _type: "faqs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: BlockContent;
};

export type Tags = {
  _id: string;
  _type: "tags";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqsReference
  >;
};

export type YouTube = {
  _type: "youTube";
  url?: string;
  caption?: string;
};

export type StlTableBlock = {
  _type: "stlTableBlock";
  stlString?: string;
  stlParsed?: string;
  caption?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | TagsReference
  | FaqsReference
  | BlogPosts
  | OpenGraph
  | Seo
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Pages
  | Faqs
  | Tags
  | YouTube
  | StlTableBlock
  | ImageGallery
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../packages/sanity/src/queries/blog-posts-by-slug-query.ts
// Variable: blogPostsBySlugQuery
// Query: *[_type == "blogPosts" && slug.current == $slug][0]{    _id,    _updatedAt,    title,    slug,    excerpt,    coverImage,    body,    publishedAt,    seo,    openGraph,    tags[]->{ _id, title, slug },    faqs[]->{ _id, question, answer }  }
export type BlogPostsBySlugQueryResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  publishedAt: string | null;
  seo: Seo | null;
  openGraph: OpenGraph | null;
  tags: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  faqs: Array<{
    _id: string;
    question: string | null;
    answer: BlockContent | null;
  }> | null;
} | null;

// Source: ../../packages/sanity/src/queries/blog-posts-meta-data-by-slug-query.ts
// Variable: blogPostsMetaDataBySlugQuery
// Query: *[_type == "blogPosts" && slug.current == $slug][0]{ seo, openGraph }
export type BlogPostsMetaDataBySlugQueryResult = {
  seo: Seo | null;
  openGraph: OpenGraph | null;
} | null;

// Source: ../../packages/sanity/src/queries/blog-posts-query.ts
// Variable: blogPostsQuery
// Query: *[_type == "blogPosts"] | order(publishedAt desc) [0...$limit]{ _id, title, slug, excerpt, coverImage, publishedAt }
export type BlogPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
}>;

// Source: ../../packages/sanity/src/queries/blog-posts-sitemap-query.ts
// Variable: blogPostsSitemapQuery
// Query: *[_type == "blogPosts" && defined(slug.current)]{ "slug": slug.current, _updatedAt }
export type BlogPostsSitemapQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: ../../packages/sanity/src/queries/pages-by-slug-query.ts
// Variable: pagesBySlugQuery
// Query: *[_type == "pages" && slug.current == $slug][0]{    _id,    title,    slug,    body,    seo,    openGraph  }
export type PagesBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  body: BlockContent | null;
  seo: Seo | null;
  openGraph: OpenGraph | null;
} | null;

// Source: ../../packages/sanity/src/queries/pages-llms-txt-query.ts
// Variable: pagesLlmsTxtQuery
// Query: *[_type == "pages" && slug.current in $slugs]{ "slug": slug.current, title, "description": seo.metaDescription }
export type PagesLlmsTxtQueryResult = Array<{
  slug: string | null;
  title: string | null;
  description: string | null;
}>;

// Source: ../../packages/sanity/src/queries/pages-meta-data-by-slug-query.ts
// Variable: pagesMetaDataBySlugQuery
// Query: *[_type == "pages" && slug.current == $slug][0]{ seo, openGraph }
export type PagesMetaDataBySlugQueryResult = {
  seo: Seo | null;
  openGraph: OpenGraph | null;
} | null;

// Source: ../../packages/sanity/src/queries/pages-query.ts
// Variable: pagesQuery
// Query: *[_type == "pages"] | order(title asc) [0...$limit]{ _id, title, slug }
export type PagesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Source: ../../packages/sanity/src/queries/pages-sitemap-query.ts
// Variable: pagesSitemapQuery
// Query: *[_type == "pages" && slug.current in $slugs]{ "slug": slug.current, _updatedAt }
export type PagesSitemapQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "blogPosts" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    title,\n    slug,\n    excerpt,\n    coverImage,\n    body,\n    publishedAt,\n    seo,\n    openGraph,\n    tags[]->{ _id, title, slug },\n    faqs[]->{ _id, question, answer }\n  }\n': BlogPostsBySlugQueryResult;
    '*[_type == "blogPosts" && slug.current == $slug][0]{ seo, openGraph }': BlogPostsMetaDataBySlugQueryResult;
    '*[_type == "blogPosts"] | order(publishedAt desc) [0...$limit]{ _id, title, slug, excerpt, coverImage, publishedAt }': BlogPostsQueryResult;
    '*[_type == "blogPosts" && defined(slug.current)]{ "slug": slug.current, _updatedAt }': BlogPostsSitemapQueryResult;
    '\n  *[_type == "pages" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    body,\n    seo,\n    openGraph\n  }\n': PagesBySlugQueryResult;
    '*[_type == "pages" && slug.current in $slugs]{ "slug": slug.current, title, "description": seo.metaDescription }': PagesLlmsTxtQueryResult;
    '*[_type == "pages" && slug.current == $slug][0]{ seo, openGraph }': PagesMetaDataBySlugQueryResult;
    '*[_type == "pages"] | order(title asc) [0...$limit]{ _id, title, slug }': PagesQueryResult;
    '*[_type == "pages" && slug.current in $slugs]{ "slug": slug.current, _updatedAt }': PagesSitemapQueryResult;
  }
}
